[package]
edition = "2021"
name = "mmap-bisect"
version = "0.1.0"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
eyre = "0.6.12"
mmap-rs = "0.6.1"
rand = "0.8.4"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
harness = false
name = "lookup-entry"
